[package]
name = "test-wasm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "running-time"
path = "src/running-time/main.rs"

[[bin]]
name = "memory-alloc-fail"
path = "src/memory-alloc-fail/main.rs"

[[bin]]
name = "happy-path"
path = "src/happy-path/main.rs"