[package]
name = "wasmtimewrapper"
version = "0.2.0"
edition = "2021"

[lib]
name = "wasmtimewrapper"
path = "src/lib.rs"
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.24.3"

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
anyhow = "1.0.66"
wasmtime = "6.0.0"
wasmtime-wasi = "6.0.0"
wasi-common = "6.0.0"